### PR TITLE
Create blockchain-floripa.md

### PR DESCRIPTION
**Pull request by MiscRay**
### Project Abstract

Blockchain Floripa creates, promotes and hosts both large-scale events and weekly meetups and educational workshops in order to help spread awareness of and grow the EOSIO community.

We have been doing so for over a year and successfully hosted two 'Blockchain Floripa Day' events with over 400 attendees to each, media coverage from Beincrypto and social media coverage from Animal Concerts and other projects. Our weekly meetups have become a great place for the community to hangout and we see new people attend almost every week who are interested in learning more about the island and crypto.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by tedcahalleos** [comment]
The Legal Structure Section must be filled out including address.  Please complete and resubmit.

### Legal Structure
- **Registered Legal Entity:** N/A
- **Registered Address:** N/A

**Comment by MiscRay** [comment]
I have now added the details of our Legal Entity and re-submitted the proposal.

**Comment by MiscRay** [comment]
@tedcahalleos Everything should now be as required for the application.

**Comment by tedcahalleos** [comment]
Please update the two LinkedIn profiles so they resolve.  They are missing the /in/ directory such as:
- https://www.linkedin.com/in/thealien/
- https://www.linkedin.com/in/lawrence-ray/

**Comment by MiscRay** [comment]
LinkedIn Profiles now corrected @tedcahalleos :)

**Comment by tedcahalleos** [comment]
Thank you. Processing continues.

**Comment by tedcahalleos** [comment]
This grant was rejected for the reasons outlined in the email to the contact person listed on the application.

**Pull request closed without merging**
