### PR TITLE
Create EOS-Cryptography-Proposal-2-b.md

### PR DESCRIPTION
**Pull request by lukapercic**
### Project Abstract

We are exploring ways to introduce new signature verification algorithms to EOS smart contracts, including RSA and algorithms based on elliptic curves.
 Through the optimizations proposed in this grant, we aim to extract more performance and significantly reduce the verification times. Additionally, we are proposing implementation of ECDSA key recovery algorithm, new elliptic curves, and the SHA-384 hashing algorithm into the ACK library, making them available for EOS smart contracts.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [x] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
Hi Luka,

Please change the the total amount to $87,000. Currently you show $87.000. 

Thank you,
Amy Burton

**Comment by ABurton22** [comment]
Hello,

This Grant Request is now received. Please do not make any further changes to this, as it will result in disqualification.

Thank you,
Amy Burton

**Comment by ABurton22** [comment]
@BenjaminGormanPMP The Grant Committee has approved this proposal. Please assign engineers to review and approve.

**Review by wanderingbort — APPROVED** [review]

**Review by DenisCarriere — APPROVED** [review]
LGTM

**Review by arhag — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]

**Comment by tedcahalleos** [comment]
This grant is fully approved and you may begin to submit Milestones.

**Pull request merged**
