### PR TITLE
BirbleAI.md

### PR DESCRIPTION
**Pull request by Birblewin**
updated again 4-4-23

### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [x] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by Birblewin** [comment]
updated 4-4-23

**Comment by Birblewin** [comment]
updated

**Comment by ABurton22** [comment]
Hello,

The Grant Request you submitted has formatting issues. With template provided, you can only delete comments; not the field names. Please do not change the formatting. You must use the form supplied.

Thank you,
Amy Burton

**Comment by Birblewin** [comment]
we are not deleting or changing any of the bold information. 
So we ran a test on another github account and forked the repo and copied your template over with making any changes, it still failed - please advise

**Comment by Birblewin** [comment]
Amy

I hope you are enjoying your Easter weekend and I'm so sorry to bother, but
could you take a look at our grant request and tell us what we are doing
wrong? We have not changed the template or deleted any of the Bold items,
but it still keeps failing to be parsed
Thanks in advance
Birble AI Team

**Comment by ABurton22** [comment]
Hello,

You didn't put your legal address. Do you have a legal entity ? If so, what is the legal address that your company is registered in?

**Comment by Birblewin** [comment]
No we do NOT have a legal entity
We are going to eventually file for INC in either USA or Canada

**Comment by ABurton22** [comment]
Hello,

Thank you. We will put this Grant Request on hold until you have a legal entity and address. Please provide a comment once this is done and we will move forward with processing your request.

Thank you,
Amy Burton

**Comment by Birblewin** [comment]
We can provide an office address, do we have to have a legal entity?

**Comment by tedcahalleos** [comment]
Yes.  You must have a legal entity as a team.

**Comment by Birblewin** [comment]
Thank you for your response
Just so I am clear, is the "Legal Entity" the only error in our application?
So if we register as a legal entity our application should be good to go?
Thank you

**Comment by ABurton22** [comment]
Yes. You must have a legal entity and address associated with that legal entity.

**Comment by Birblewin** [comment]
Go it
so once we correct this legal entity and address associated with that legal
entity
we will be good to go?

**Comment by tedcahalleos** [comment]
Once we have that, we can begin the actual processing of that grant.  Right now we are just validating all the input fields.  It would still need to be approved by the Grant Committee, and if they approve, then the Grant Technical Evaluators.  Up until now, we were just making sure the format was correct and all the necessary fields were there.

**Comment by Birblewin** [comment]
I understand
we will work on setting up legal entity
Thank you

**Comment by ABurton22** [comment]
Closing due to 2 weeks pending Legal Entity creation. Please resubmit once Entity is created.

**Comment by Birblewin** [comment]
its says our grant was rejected, should we even bother resubmitting?

**Pull request closed without merging**
