### PR TITLE
Smart Contract Developer's Handbook

### PR DESCRIPTION
**Pull request by cc32d9**
### Project Abstract

This grant application aims to deliver a comprehensive guide for smart contract developers. The writing is already in progress, and the work is published at https://cc32d9.gitbook.io/eosio-smart-contract-developers-handbook/

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [ ] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [ ] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [ ] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [x] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Review by 766C6164 — COMMENTED** [review]
I have no doubt in competence of the team and value of such handbook, great work!

**Review by nsjames — APPROVED** [review]

**Review by 766C6164 — APPROVED** [review]

**Comment by arhag** [comment]
I think @766C6164's suggestion of breaking up the 4 month milestone is a good one, though not essential. 

For example, we were thinking of the first milestone being a draft of the handbook with completed technical content, but that has not yet had the editing and revising to have it ready for actual publishing. And then the second milestone would be the final one for the grant.

I believe we are open to a split into two milestones, and so if you see benefit in this sort of split so that you can get evaluator feedback earlier in the process before more time and money is spent proofreading and editing, please revise the grant proposal and we can re-review and approve.

If you are fine with the proposal as is, then I am okay with it too. In fact, I will add my approval now.

**Review by arhag — APPROVED** [review]

**Comment by cc32d9** [comment]
@arhag 4 months is the approximation for total work which has been started a long time ago. So, the plan is to deliver the end product by early Autumn. My colleague that will do the proofreading will be back to work in early September, and most of content will be ready by that time.

**Review by DenisCarriere — APPROVED** [review]
I do strongly believe that cc32d9 and the Zaisan team has the capability to offer high quality work to develop an EOSIO smart contract developer handbook.

Valuable content has already been published in the referenced GitHub repo.

**Comment by tedcahalleos** [comment]
The Grant Evaluators have approved your application and you have now moved to the milestones phase. Please see the email sent to you.  Congrats.

**Pull request merged**
