### PR TITLE
Grant Proposal for Antelope Developers Guidebook targeted at Javascri…

### PR DESCRIPTION
**Pull request by dougbutner**
…pt Developers

### Project Abstract
The Antelope Developers Guidebook aims to onboard the massive Javascript developer community to Antelope / EOSIO by showing how easy it can be to interact with the blockchain(s) using Javascript and open source contracts. This Gitbook-based guidebook will include an exciting quickstart-style introduction, plenty of code samples, and a review of the best open-source contracts, giving any Javascript dev a quick yet profound introduction to the ecosystem and technology. 

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [x] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [x] Other: ___Antelope Developers Telegram____

### CODE REVIEW

**Comment by ABurton22** [comment]
Hello,

Your application is missing the Open Source question. Please add that back in and answer accordingly.

Thank you,
Amy Burton

**Comment by ABurton22** [comment]
Grant Request is now received. Please do not make any further changes, as it will result in disqualification.

Thank you,
Amy Burton

**Comment by dougbutner** [comment]
Hi Amy, 

I have updated the grant proposal to include that line with Yes, everything is open source including all the code samples and the text. 

I know it's supposed to be one commit per request, so if you need me to cancel this pull request, re-fork the repo, and re-pull as one commit, let me know. 

`| 0a. | License | Creative Commons BY-SA 4.0 |`

Creative Commons BY-SA 4.0 is the current license as written in the proposal. If the EMF would like me to change that, just let me know. 

Thanks, 
- Douglas

**Comment by dougbutner** [comment]
Just saw your second message. I won't make other changes.

**Comment by ABurton22** [comment]
Grants not approved.

**Comment by dougbutner** [comment]
> Grants not approved.

Thanks. Please try to shorten your feedback time in the future.

**Pull request closed without merging**
