### PR TITLE
Legacy_Ledger.md

### PR DESCRIPTION
**Pull request by jruffer**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [ ] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [ ] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [ ] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
You must use the latest version of the standard template and not delete any of the required fields. This includes proposed milestones and costs for each (plus total cost).

Failure to update and use the correct milestone will result in the application being rejected.
Thanks,

Amy Burton

**Comment by ABurton22** [comment]
Hello,

Following up to the above message. If you are still interested in applying for a Grant Request, please make sure to use the latest version of the standard template and not delete any of the required fields including proposed milestones and costs for each (plus total cost). 

If not, please close out your Grant Request.


Best,
Amy Burton

**Comment by jruffer** [comment]
Not sure why I am not getting notifications on this. My apologies I'll get this updated.

**Comment by jruffer** [comment]
I might need help here. What is missing? I have the latest version and only took out the < sections as per the readme.

**Comment by ABurton22** [comment]
Please resubmit your file as a .md

Per the Application Process, Line 3, Name the new file after your project: myproject_name.md. Please make sure to put it in the applications directory. Make sure your filename does not have any spaces in it and ends with the .md extension.


Thank you,
Amy Burton

**Comment by jruffer** [comment]
Done.

**Comment by ABurton22** [comment]
Hello,

Please complete all the information in milestone summary. It looks like the below is missing there:

**Total Estimated Duration:**
**Full-Time Equivalent (FTE):**
 **Total Costs:**

Also, please provide a complete address. Currently it only shows: Archer Florida 32618

Thank you,
Amy Burton

**Comment by jruffer** [comment]
I am happy to do KYC through secure channels but not putting addresses in the clear.

**Comment by jruffer** [comment]
I see all of the milestone summary data there. What am I missing?

**Comment by tedcahalleos** [comment]
You are still missing these three fields below the summary.  These add up the totals from the milesones below it.  Where on your application are you showing the Total Costs as they would be if you had shown them as below.  Please make sure to use the original lines from the template - as an automated parser is kicking this out since these are missing...
Ted Cahall

### Milestone Summary

- **Total Estimated Duration:** 2 months 
- **Full-Time Equivalent (FTE):** 2 FTE
- **Total Costs:** 12,000 USD

**Comment by jruffer** [comment]
Did it work?

**Comment by tedcahalleos** [comment]
Hi James,
I was able to KYB the business name and see you are in the state of DE.  So we will proceed with processing the grant.
Ted Cahall

**Comment by jruffer** [comment]
updated

**Pull request closed without merging**
