### PR TITLE
Grant Proposal:  Moonboat NFT marketplace

### PR DESCRIPTION
**Pull request by moonboatnft**
### Project Abstract
Moonboat(Moonboat NFT Marketplace) is a decentralized, open and extensible NFT Marketplace built on EVM and EOS, relying on the high performance, security and reliability of EOS, bringing rich digital collectibles to EOS and EVM eco-users. Through Moonboat users can easily and quickly create, trade and auction digital collectibles.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [x] Social Media
- [x] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by moonboatnft** [comment]
For policy reasons, it is not convenient to disclose legal entity, we send information to the email grants@eosnetwork.com

thank you.

**Comment by ABurton22** [comment]
Please provide legal entity name and address to Grant request and resubmit.

Thank you,
Amy Burton

**Comment by moonboatnft** [comment]
@ABurton22  Legal entity information has been updated

**Comment by moonboatnft** [comment]
We will close this grant, and will resubmit。

**Comment by moonboatnft** [comment]
I'm sorry, I did update the content of the last PR, but according to the response, the content of the internal review was not updated, so I closed this PR and opened a new one. now I'm reopening this PR, please help me update the content, thank you very much!

**Comment by moonboatnft** [comment]
@ABurton22 Hello, did you see the above reply, please help, it's important, thanks!

**Pull request closed without merging**
