### PR TITLE
Knockout Wars Game

### PR DESCRIPTION
**Pull request by GAMI-STUDIO**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [x] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
@BenjaminGormanPMP  Grant has been Committee Approved. Please assign reviewers.

Thank you,
Amy Burton

**Review by nsjames — APPROVED** [review]

**Comment by nsjames** [comment]
lgtm

**Review by taokayan — APPROVED** [review]
Look good to me.

**Review by wanderingbort — APPROVED** [review]

**Comment by BenjaminGormanPMP** [comment]
Hi @uddina, can you please complete the commit for "Completed Application" and "Text changes" to support PR merge?  Thanks.

**Review by uddina — APPROVED** [review]

**Review by uddina — APPROVED** [review]

**Review by uddina — APPROVED** [review]

**Comment by BenjaminGormanPMP** [comment]
> > 
> 
> Hey @BenjaminGormanPMP , @ABurton22
> 
> I have tried to merge things, but it looks like it pulled more files into our fork, and now the scripts are complaining. Could you help with what needs to be done to solve this.
> 
> Thanks

@GAMI-STUDIO Can you please sign the license agreement?  This is needed to support PR merge.

**Comment by tedcahalleos** [comment]
Unfortunately this grant application shows it was part of a Token Sale.   We cannot approve grants that are part of a Token Sales as part of the rules stated [here}(https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/minimum-requirements.md).

Therefore we have marked this grant as `Rejected`.  We will contact you in email to let you know how to potentially work with the EOS Network Ventures team on a potential investment from them.
Ted Cahall
ENF Grant Operations

**Comment by tedcahalleos** [comment]
Closing as `Grant-Rejected` due to being part of a Token Sale.

**Pull request closed without merging**
