### PR TITLE
Cryptolions 50k grant for www.MSIG.app - create msig_app.md

### PR DESCRIPTION
**Pull request by TarasCL**
### Project Abstract

It is too complicated for a novice to manage multi signatures. We will solve this! And for experts - we have templates that make your daily multisig transactions easy. Save your time for more important things! Blockchain gives us a new sense of personal ownership. Now we also move into group ownership, DAO, cooperation, making decisions together with somebody, etc. We are developing MSIG app (https://msig.app/jungle), which helps both new and pro users to manage multi-signature transactions. Pomelo: https://pomelo.io/grants/msig.app

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by TarasCL** [comment]
test comment

**Comment by tedcahalleos** [comment]
> I got an issue with this grant application, related to the fact that the repo is private.
> 
> Here is the public repo: https://github.com/CryptoLions/MSIG_tool
> 
> I am not sure what is the best way for me to fix this issue. Should I create a new PR for this, or some other way of fixing this is better?

Please make a separate commit adding that new link into the msig_app.md file.  Also explain in the application to the Grant Committee why you have a private UI repo per the application not checking the "Open Source" box in the Pull Request template and the Telegram note below:

So our plan was like this:
Open-source system smart-contract calls in a separate module (npmjs) that can be reused by other devs.
Closed-source the rest of the UI only.

**Comment by TarasCL** [comment]
Updated this PR, thank you.

**Comment by TarasCL** [comment]
I will reopen this grant today, this time it will be completely open-sourced, as this was the main reason for rejection.
Note: This will be the only change, so you maybe may save time and use the previous translation, to not translate it 2nd time.

**Pull request closed without merging**
