### PR TITLE
Create subdeeply-aplication.md

### PR DESCRIPTION
**Pull request by thiangm**

### CODE REVIEW

**Comment by tedcahalleos** [comment]
There is a broken link to your figma files on line 229.  It has the subdeepy domain prepended to the figma URL as shown here:
`https://subdeeply.comhttps://www.figma.com/file/3ECnQsptS5BIhl4pzhGJ9m/Subdeeply-Onboarding-app-UI-Design?node-id=106%3A259`.  Could you please fix that so the URL functions properly?

Also it is not clear why on line 115 why you inlcuded a reference to localhost: `http://localhost:4449/#/`  Were you trying to show how to access the installed files on port 4449?  Possibly some documentation on that or remove the spurious reference?

**Comment by thiangm** [comment]
- There is a broken link to your figma files on line 229. It has the subdeepy domain prepended to the figma URL as shown here: `https://subdeeply.comhttps://www.figma.com/file/3ECnQsptS5BIhl4pzhGJ9m/Subdeeply-Onboarding-app-UI-Design?node-id=106%3A259`. Could you please fix that so the URL functions properly?

Line 229 was corrected and the link to the figma files is now fixed.

- Also it is not clear why on line 115 why you inlcuded a reference to localhost: `http://localhost:4449/#/` Were you trying to show how to access the installed files via port 4449? Possibly some documentation on that or remove the spurious reference?

In line 115 added reference to localhost mainly to give a reference to the development process of the platform, it is important that we check the speed and its operation as proposed before launching it. We cannot incorporate a platform that does not work properly.
It allows us to simulate a connection by skipping the Network: the connection stays entirely on the local host of the system.

**Comment by tedcahalleos** [comment]
Thank you for the updates.  We are processing your application in the Grant Committee.

**Comment by thiangm** [comment]
- Thank you for the updates. We are processing your application in the Grant Committee.

Thanks @tedcahalleos for the update, I'll wait waiting for more answers.

**Comment by tedcahalleos** [comment]
Hi Thian,
We regret to inform you that your ENF Grant Application was rejected.  We sent you an email letting you know the reasons.  We wish you the best of luck with your application and future submissions to the ENF.

**Comment by thiangm** [comment]
> Hi Thian,
> We regret to inform you that your ENF Grant Application was rejected.  We sent you an email letting you know the reasons.  We wish you the best of luck with your application and future submissions to the ENF.

    Thanks for the answer, from the Subdeeply team we will work without the expected funding from the ENF Grants and we bring that we are up to the Grants for a future application.

**Pull request closed without merging**
