### PR TITLE
Block Hotel

### PR DESCRIPTION
**Pull request by cryptotwilight**
### Project Abstract
Block Hotel enables Hotels to issue decentralized Hotel Bearer Tokens. These Hotel Bearer Tokens are traded and eventually presented back to the Hotel in exchange for a stay at the Hotel. The Hotel Bearer Tokens divorce the conditions of stay from the conditions of purchase allowing the guest or traveller to leverage blockchain enabled forms of financing when dealing with plan changes. The aim of Block Hotel is to introduce a new level of travel flexibility in the face of ever more unpredictable travel. Built on EOS this will in turn open up new avenues of stability, commerce and finance. 

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [x] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [x] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by cryptotwilight** [comment]
Something went wrong help?

**Comment by cryptotwilight** [comment]
Hi Guys, please do let me know if there is anything I can do, thank you

**Comment by ABurton22** [comment]
This Grant Request has been received. Please do not make any further changes to this, as it will result in immediate disqualification.

Thank you,
Amy Burton

**Comment by ABurton22** [comment]
Grant not approved.

**Comment by cryptotwilight** [comment]
Any insights into why?

**Comment by cryptotwilight** [comment]
Not to worry just got mail

Thank you

**Pull request closed without merging**
