### PR TITLE
Scry protocol 

### PR DESCRIPTION
**Pull request by pr0toshi**
### Project Abstract
An Open, Decentralized and Permissionless Framework for Bringing On-Demand Web2 Data to Web3
Morpheus is a framework that allows developers to request any API from web2, directly onchain for their web3 apps. This tool enables real-time data requests, any API and data to be used, and can be used on any EVM network. Morpheus has been designed to make it easier for developers to build decentralized applications that can interact with the real world, thereby bridging the gap between web2 and web3.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [x] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by pr0toshi** [comment]
Scry

**Comment by ABurton22** [comment]
Hello,

Please provide your EOS address and resubmit. 

Thank you,
Amy Burton

**Comment by pr0toshi** [comment]
Is EOS EVM address not accepted?

**Comment by ABurton22** [comment]
Please fix the formatting in Milestone 3 so that it is in the table format like the other tables.

Thank you,
Amy Burton

**Comment by pr0toshi** [comment]
> Please fix the formatting in Milestone 3 so that it is in the table 1,2 and 4format like the other tables. If not, we will close out the request.
> 
> Thank you, Amy Burton

Has been updated. Ready for review

**Comment by ABurton22** [comment]
Hello,

Your EOS address is still not showing.

**Comment by pr0toshi** [comment]
> Hello,
> 
> Your EOS address is still not showing.

Was defnately there but assume you have a bot that pulls from the applications so hopefully fixed now.

**Comment by pr0toshi** [comment]
> Hello,
> 
> Your EOS address is still not showing.

Hey just wanted to confirm the applications all good now?

**Comment by ABurton22** [comment]
Yes. It is pending Committee Review.

Thank you,
Amy Burton

**Comment by pr0toshi** [comment]
Hey there whats the rough ETA, have seen that pull requests that were opened after have been approved already before us. Just wanting to know when we'll know if the infrastructure is desired to include in our launch plans

**Pull request closed without merging**
