### PR TITLE
EOS Hub Grant Proposal

### PR DESCRIPTION
**Pull request by LuukDAO**
### Project Abstract
[EOSHub.md](https://github.com/eosnetworkfoundation/grant-framework/files/12402016/EOSHub.md)

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x ] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [ x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x ] I have read and understood the:
  - [ x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [ x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x ] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x ] An EOS address for the payment of the milestones is provided inside the application.
- [x ] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x ] The software delivered for this grant will be released under an open-source license specified in the application.
- [x ] This project has NOT been part of a token sale or NFT sale.
- [x ] The initial PR contains only one commit (squash and force-push if needed).
- [x ] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [x ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
Hello,

In reviewing your application, I found that your Grant Request needs a valid address. If you don't feel comfort able putting it in your application, you can email it to us at grants@eosnetwork.com. However, we do need a valid address to move forward.

Thank you,
Amy Burton

**Comment by LuukDAO** [comment]
> Hello,
> 
> In reviewing your application, I found that your Grant Request needs a valid address. If you don't feel comfort able putting it in your application, you can email it to us at [grants@eosnetwork.com](mailto:grants@eosnetwork.com). However, we do need a valid address to move forward.
> 
> Thank you, Amy Burton

Hi Amy!

Our full address is Presidente Romule Betancourt Boulevard 16 C - the island doesn't use ZIP codes, hence why there is no ZIP CODE. 

Full address:
Presidente Romule Betancourt Boulevard 16 C
Willemstad, Curacao

**Comment by LuukDAO** [comment]
Hey @ABurton22,

We wanted to provide an update on the grant - as we have been able to progress the project further in the past weeks!

We created a separate EOS page that contains the top projects from EOS and EOS EVM: https://www.prime.xyz/eos.

If our grant is approved, we can make an event better and tailor-made platform with a native domain (we already purchased some EOS Hub domains) + produce the blogs, guides, and ecosystem reports to help drive ecosystem value. 

We look forward to any questions or feedback from the Grants Committee!

**Comment by ABurton22** [comment]
Grant not approved

**Pull request closed without merging**
