### PR TITLE
EOS VISION AND REDDIT 2

### PR DESCRIPTION
**Pull request by Creamyvanill**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [X] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [X] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [X] I have read and understood the:
  - [X] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [X] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [X] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [X] An EOS address for the payment of the milestones is provided inside the application.
- [X] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [X] The software delivered for this grant will be released under an open-source license specified in the application.
- [X] This project has NOT been part of a token sale or NFT sale.
- [X] The initial PR contains only one commit (squash and force-push if needed).
- [X] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [X] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by tedcahalleos** [comment]
The Milestone Summary Section was deleted and needs to be put back - even with a single Milestone as it breaks the parser.  Please cut and paste it from the most recent version of the application_template.md and add it back in the correct location with the total information.  We need it to be cut and paste as typos and spelling issues will also cause the parser to break.  Thanks.

**Comment by Creamyvanill** [comment]
Hello! for some strange reason i never received notifications about this, i'll fix it right now.

**Comment by ABurton22** [comment]
Hello,

We are still looking for the Grant Milestone Summary section to be added back in. Please correct this within the next week or we will close the pull request.

The Milestone Summary Section was deleted and needs to be put back - even with a single Milestone as it breaks the parser. Please cut and paste it from the most recent version of the application_template.md and add it back in the correct location with the total information.


Thank you,
Amy Burton

**Comment by tedcahalleos** [comment]
Hi,
I see you added in the Milestone Summary section.  That is good - except it does not add up to the same numbers as the only Milestone.  It is a summary of all of the Milestones - which in your case is 1 Milestone. But it still needs to be the sum of that one Milestone.  Please correct and resubmit.
Thanks,
Ted

**Comment by Creamyvanill** [comment]
I already added the addition of milestones, but I'm still having grammar problems.

**Comment by tedcahalleos** [comment]
Hi,
This is good enough.  Amy - it is OK to translate it now.
Thanks,
Ted Cahall

**Comment by Creamyvanill** [comment]
Gracias!

**Comment by Creamyvanill** [comment]
Hi guys! Everything okay here? they need something more?

**Comment by Creamyvanill** [comment]
Hello guys! Greetings.

Let's start with the approvals? Do you need anything?

I'm paying attention.

@BenjaminGormanPMP @stephenpdeos

**Comment by ABurton22** [comment]
Hi Veronica,

We will let you know if anything further is needed from you. Our approval process for this Grant Request is underway and being worked on. Thank you for your follow up.

Best,
Amy Burton

**Review by DenisCarriere — APPROVED** [review]
Grant looks good on a technical side.

Looking forward to seeing reports metrics as one of the deliverables.

👍

**Review by DenisCarriere — APPROVED** [review]
Grant looks good on a technical side.

Looking forward to seeing reports metrics as one of the deliverables.

👍

**Comment by BenjaminGormanPMP** [comment]
Confirmed PR reviews by both @nsjames and @DenisCarriere. FYI @stephenpdeos. Assigning issue to @ABurton22.

**Pull request merged**
