### PR TITLE
Oldtimers Offer

### PR DESCRIPTION
**Pull request by oldtimers-offer**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [x] Social Media
- [x] EOSNetwork.com
- [x] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by oldtimers-offer** [comment]
adding Oldtimers Offer in applications folder

**Comment by tedcahalleos** [comment]
There are several issues with this grant application that must be fixed before it can be processed.
- the Pull Request Template should be filled out properly (the check boxes)
- Several of the main fields including Token Sale and Open-Source fields from the current template are missing.  Please add them back.  Please make sure you are using the latest version of the application template when submitting - as it has changed as we needed additional processing information or formatting.  It looks like you used an old template from an older version of the repo;

These fields need to be included in the top section:
- **Project Name:** Name of your project (e.g. Anchor Wallet)
- **Team Name:** Legal name of your team (e.g. Greymass, Inc.)
- **EOS Payment Address:** EOS payment address
- **[Level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels):** 1, 2 or 3
- **Pomelo Grant(s):** List URL(s) to Pomelo grants for your team (or list N/A for non-applicable)
- **Project is Open-Source:** Yes/No
- **Project was part of Token sale:** Yes/No
- **Repository where Project resides:** https://github.com/<your_organisation>/<project_repo>

There are subtle changes throughout the latest version of the application template.  Please pull that, and update your information into that version of the template.

**Comment by oldtimers-offer** [comment]
Dear Ted,

We made suggested changes. 
Please, take a look when you have time.

Beste regards,
Oldtimers Offer Team

**Review by oldtimers-offer — COMMENTED** [review]
The latest version of the application template

**Comment by ABurton22** [comment]
Grant request has been rejected by Grant Committee. Closing out pull request.

Thank you,
Amy Burton

**Pull request closed without merging**
