### PR TITLE
Noahark DeFi Grant application on Trust EVM

### PR DESCRIPTION
**Pull request by NoaharkEVM**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ ] **Level 2**:  Up to $50,000, 3 approvals
- [x] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [x] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by NoaharkEVM** [comment]
Hi, friend. we already signed, please check

**Comment by tedcahalleos** [comment]
Confused by the "Yes*" label on the "***Open-Source**" label.  The project must be 100% Open-Source or it will be rejected.

Can you please explain the reason for the asterisk on the Yes response?

The Milestones are not separated into sections that follow the template guidelines.  Please do that or the application will not be processed.

**Comment by NoaharkEVM** [comment]
> Confused by the "Yes*" label on the "***Open-Source**" label. The project must be 100% Open-Source or it will be rejected.
> 
> Can you please explain the reason for the asterisk on the Yes response?
> 
> The Milestones are not separated into sections that follow the template guidelines. Please do that or the application will not be processed.

Hello, Ted. How are you doing? I Just DM some EOS friends asking about this grant.
Thank you for your feedback, here is the update:

1. Open source: Yes*. We already removed the * mark. We are able to open source any time you request. So for open source, no problem, we will be 100% open source.

2. About milestone form, we already update according to the examples in the template.md, check if it meets your requirements. 

Thank you very much

Kind regards

Noahark

**Comment by tedcahalleos** [comment]
You have put the entire $195,000 USD project into a single milestone.  The grant amount is very large - so we would want to see it broken down into multiple milestones that would explain exactly what is being built and how to test each one.  I would recommend at least 4 milestones.  Please consult the template to see how to do this.

**Comment by NoaharkEVM** [comment]
Dear Ted:

Thanks for your reply. We already updated, please check:
https://github.com/NoaharkEVM/grant-framework/blob/main/applications/Noahark.md

Thank you for your advice, we have modified it according to the template.
However, since the development project is a progressive process, the items
look relatively similar, but in fact the technical details inside
different, and the development of the module is an integrity, it is not
easy to completely split and describe, however, we still present as 3
milestones based on our Noahark project, please check. Thanks.

Kind regards

Noahark

**Comment by NoaharkEVM** [comment]
Dear Ted:

@tedcahalleos 

Thank you for your advice, we have modified it according to the template. However, since the development project is a progressive process, the items look relatively similar, but in fact the technical details inside different, and the development of the module is an integrity, it is not easy to completely split and describe, however, we still present as 3 milestones based on our Noahark project, please check. Thanks.

Kind regards
Noahark

**Comment by NoaharkEVM** [comment]
@tedcahalleos

Hello, Ted. How are you? We have already re-write the grant application based on your advice. Our team needs some upfront support for that. So could you please help check the application, thank you very much

My Telegram account is:

https://t.me/noaharkevm

You can also contact me there. Thanks

**Comment by NoaharkEVM** [comment]
> Sorry for the delay in processing your application. You are still missing the Github accounts of your team members so the Grant Evaluators can see the experience of your team. We were on a delay for the US year end holiday and are on a short delay due to the lunar new year. But if you can get those Github accounts listed where they are requested in the template, we will get them processed as soon as the teams involved and the Grant Committee return from their Lunar New Year break. Deleting sections of the template delays the process. You should check that all sections are matching the latest template and ensure you have filled them out.

Dear Ted:

Thanks for the reply. I already updated the team members Github links, you can click it on and check it out. I think their activity not limited to Github.com but also some other places. Our core team members all have experience in Top blockchain projects for several years and they are pretty good. We can surely communicate with your ENF tech team in private chat if necessary for the next step. Anyway, thanks for reminding us and appreciated your help very much. If you have any feedback, welcome to reply on this comments or send an E-mail to our Google mail

Kind regards

Noahark Team

**Comment by NoaharkEVM** [comment]
Dear Ted:

Thanks for the reply. I already updated the team members Github links, you
can click it on and check it out. I think their activity not limited to
Github.com but also some other places. Our core team members all have
experience in Top blockchain projects for several years and they are pretty
good. We can surely communicate with your ENF tech team in private chat if
necessary for the next step. Anyway, thanks for reminding us and
appreciated your help very much. If you have any feedback, welcome to reply
on this comments or send an E-mail to our Google mail

Kind regards

Noahark Team

**Comment by tedcahalleos** [comment]
The developer repos are basically empty.  As is the project repo.  I will process it but this does not give much information to the evaluators if it makes it that far.

**Comment by NoaharkEVM** [comment]
> 

Hello, Ted. Thanks for proceed it. Due to blockchain anonymity, their Github information won't reveal everything. However don't worry, our team is good, we will definitely communicate with evaluators more to present ourselves during our process. Again, thanks for your support. If there is any update, don't hesitate to contact us again. @tedcahalleos

**Comment by NoaharkEVM** [comment]
Hello, Ted. Thanks for proceed it. Due to blockchain anonymity, their
Github information won't reveal everything. However don't worry, our team
is good, we will definitely communicate with evaluators more to present
ourselves during our process. Again, thanks for your support. If there is
any update, don't hesitate to contact us again. @tedcahalleos

**Comment by NoaharkEVM** [comment]
@tedcahalleos

Hello, Ted. This is Noah DeFi on Trust EVM. Thank you for your help so far. Recently I received a message from Trust EVM management that they are asking about the progress of grant Noah. Actually, because Noah is a big project involves investment, Noah team and Trust EVM team has been in contact for some good time. We were working good. Since it is already a pass from the Step 1 ENF grant selection, is there anything we can do so that we can be on the list as well. 

The Trust EVM management team said they already saw that "EVM Name Service" is already on the list, while our "Noah Swap" is not yet. 

https://github.com/eosnetworkfoundation/grant-framework/tree/main/applications

https://github.com/eosnetworkfoundation/grant-framework/pull/109

Appreciated if you could help. 

Kind regards

Noah Team

**Comment by ABurton22** [comment]
This grant was rejected by the Grant Committee. Please see email that was sent to you.

Thank you,
Amy Burton

**Pull request closed without merging**
