### PR TITLE
8Bit Arcade 'Pull Request' to EOS grant application

### PR DESCRIPTION
**Pull request by Russell-Bryant**
### Project Abstract

8Bit Arcade is a web2 and web3 gaming platform with mobile integration.
We are predominantly an incubator for indie game developers but will also be a gaming hub for games to be hosted on.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approval
- [x ] **Level 3**:  Up to $200,000, 4 approval

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [ ] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [ ] I have read and understood the:
  - [ ] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [ ] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [ ] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [ ] An EOS address for the payment of the milestones is provided inside the application.
- [ ] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [ ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ ] This project has NOT been part of a token sale or NFT sale.
- [ ] The initial PR contains only one commit (squash and force-push if needed).
- [ ] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [x ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [x] Other: __EOS team member_____

### CODE REVIEW

**Comment by Russell-Bryant** [comment]
First time using a Pull request, so I'm hoping its worked okay.
Regards, Russell Bryant

**Comment by ABurton22** [comment]
Hello,

Per our Grant Guidelines, We do not award grants for projects that have been the object of a successful token sale. Your application has "yes" selected for token sale. If this is not correct please change. If this is correct and it was part of a token sale, please close your Grant Request.

Thank you,
Amy Burton

**Comment by Russell-Bryant** [comment]
Hello,
It was not a successful launch. I address this further down the application.
Regards, Russell

**Comment by ABurton22** [comment]
Closing Grant Request as it was part of token sale. The sale was not successful as per applicant, but Grant Request Guidelines do not permit.

**Pull request closed without merging**
