### PR TITLE
Application for grant Qlone.ai

### PR DESCRIPTION
**Pull request by QLONEAI**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
>
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
Hello,

Your Grant Request is missing the following information:

Grant Request Level
EOS Address

Also, your request shows that this is not open sourced. Per our guidelines, all requests must be open-source. Please review and resubmit as open source if it is, if it isn't please close the request as we can not move forward.


Thank you,
Amy Burton

**Comment by ABurton22** [comment]
Closing out this grant request due to no changes being made.

Thank you,
Amy Burton

**Comment by QLONEAI** [comment]
Hello @ABurton22! 

We made changes as you asked the last week, in committing No. [65b79d7] - (https://github.com/eosnetworkfoundation/grant-framework/pull/176/commits/65b79d79a37a85574fc1a984b437b8fc15731afd)https://github.com/eosnetworkfoundation/grant-framework/pull/176/commits/65b79d79a37a85574fc1a984b437b8fc15731afd

Please check again, and if we updated the information incorrectly, let us know what to do next. Can we re-apply?

Best regards, 
Qlone AI team.

**Comment by ABurton22** [comment]
Hello,

You are still missing the Entity Address and the level grant request you are requesting. Please make sure the parcer is not broken and it is identical to the application.

THank you,
Amy Burton

**Comment by QLONEAI** [comment]
Hello, we have already filled in level 2 on grant request application. Also Entity Address provided already in Legal Structure/Registered Address section, in this commit https://github.com/eosnetworkfoundation/grant-framework/pull/176/commits/65b79d79a37a85574fc1a984b437b8fc15731afd If you need I can reapply with a new pull request.

**Comment by QLONEAI** [comment]
Hello, reminding you to check our grant proposal! Let us know if you need
something more.

**Pull request closed without merging**
