### PR TITLE
Create wootzapp.md

### PR DESCRIPTION
**Pull request by sandys**
### Project Abstract

Onboarding the next billion users to Blockchain. Are you going to ask them to use a desktop browser extension ? Most people dont have a desktop - especially in Asia. Their only device of accessing the internet is their mobile phone. That's why you need a web browser build ground up for crypto (and which implements all of the browser specific EIP). The user does not need a wallet app and a browser app separately.

Wootzapp is the way that a hundred million NEW users will use the CSPR chain for the *First Time*. In fact, by making their first account on CSPR, we will lead the default chain experience to be CSPR first. We want people to mint their first CSPR NFT within 30 seconds of signing up for Wootzapp 

we are a fully opensource (https://github.com/wootzapp/wootz-browser) mobile browser that is built for crypto. The wallet and everything else is integrated in. We have also implemented several EIP that were specific to browser integration and were waiting for Chrome to implement in.
for a new user to crypto - especially the billions of users in Asia who do NOT have a desktop computer or browser extensions - the way to use crypto is simply "use this browser, it has everything built in". 
If you visit a dapp website, our proprietary javascrip-native bridge will popup and all the web3 functions will work automatically.

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [ X] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [ x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applicatxions` directory.
- [ x] I have read and understood the:
  - [x ] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x ] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x ] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x ] An EOS address for the payment of the milestones is provided inside the application.
- [x ] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x ] The software delivered for this grant will be released under an open-source license specified in the application.
- [ x] This project has NOT been part of a token sale or NFT sale.
- [ x] The initial PR contains only one commit (squash and force-push if needed).
- [ x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ x] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ x] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by sandys** [comment]
Hi Ted
So we are a mobile app. Not a web based dapp. I'm not sure how to to answer
those - since they were very oriented towards web based testing.

I can try to answer. Would that be ok ?

**Comment by tedcahalleos** [comment]
Sure that is OK.  But we need to have all the fields that were removed put back in and answered as well.  There should be some server code that works with the blockchain in addition to the app code in the phone.  We are likely mostly interested in that part in terms of testing and milestones.

**Comment by sandys** [comment]
> Sure that is OK. But we need to have all the fields that were removed put back in and answered as well. There should be some server code that works with the blockchain in addition to the app code in the phone. We are likely mostly interested in that part in terms of testing and milestones.

actually no server code. think of us as a Google Chrome with an integrated Metamask. With deep EOS Network support. I do understand that most of your grant application will be dapps or server side. But my goal is geared towards onramp for the billions of users who dont speak English and who are new to the crypto ecosystem. My goal is to have EOS be their first blockchain.

However, i will try to fit in with your application template to answer it as best as i can.

**Comment by tedcahalleos** [comment]
Hi,
Your total cost does not equal your Milestones.  The Milestones are more expensive and in ranges.  The numbers need to be exact and need to add up.  The Legal Entity address needs a full street address, not just city and state.  
Please correct and resubmit.

**Comment by tedcahalleos** [comment]
Closing due to lack of updates per comments above.

**Pull request closed without merging**
