### PR TITLE
Cambiatus Grant application

### PR DESCRIPTION
**Pull request by lucca65**
### Project Abstract

Following up our Pomelo season 3 campaign, we are now applying for a grant to help us develop our Roles and Permissions feature. This will allow our communities to have decentralized governance by assign roles to its members. Those roles may have permissions that allows them to participate on certain parts of the community, such as a validator for claims, or a seller on the decentralized shop. This will also be our baseline for creating a governance model based on participation, involvement and knowledge. 
 
With those features we can begin to experiment with our communities (with over 9k users) to help them build User Journeys,  a path to earning roles in a community, and decentralized voting systems, to allow governance and active participation to really flourish 

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to $10,000, 2 approvals
- [x] **Level 2**:  Up to $50,000, 3 approvals
- [ ] **Level 3**:  Unlimited, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [x] Other: Active participation on the community channels such as telegram and meetups

### CODE REVIEW

**Comment by tedcahalleos** [comment]
Please correct the following grant application template issues:
- Please add back in the **Milestone Summary** Section plus it's three subsections listed below with the original formatting
  - **Total Estimated Duration:** XX months
  - **Full-Time Equivalent (FTE):** YY FTE
  - **Total Costs:** NN,000 USD
- Please restore the original formatting the the **Legal Structure**
  - **Registered Legal Entity:** Name of your registered legal entity. (e.g. Greymass, Inc.)
  - **Registered Address:** Address of your registered legal entity.
- It is unclear if you are asking for $60,000 USD for the 6 milestones in summary.  If so, you are grant level 3 and not 1 as listed.

**Comment by lucca65** [comment]
@tedcahalleos thanks for the review. All points were corrected!

**Comment by tedcahalleos** [comment]
May I ask for one additional change per Milestone please?  If you could explain to the Grant Evaluators how they would test completeness of each of these milestones, it would be appreciated.  Each one will be paid separately upon verification of code completion and correctness.  If you can point to a URL to demonstrate functionality or a Docker image that can be downloaded or built for each step, that would be great.  Thanks.  We are proceeding with the grant to the Grant Committee - the first step in the process.

**Comment by lucca65** [comment]
Done! I've added individual instructions, since they are different on each milestone. Two milestones are focused on community building, teaching our users how to use the features we've develop. Let me know if it can be more complete!

**Comment by tedcahalleos** [comment]
The grant was rejected for reasons listed in the email sent to the contact person listed in the application.

**Pull request closed without merging**
