### PR TITLE
DaoSwap

### PR DESCRIPTION
**Pull request by eosdaoswap**
### Project Abstract

> Please provide a brief description of your project here summarising key points (1-2 paragraphs).
> DaoSwap is a decentralized project platform that provides EOS users and project teams with various services, such as trading, mining, wealth management, account registration, CPU purchase, memory purchase, resource free transfer, red envelope sending, anonymous banking, NFT trading, and other functions; Among them, anonymous banks and pomelo red envelopes are their innovative projects. For example, sending red envelopes is an important social behavior of Chinese people, which can effectively improve user activity. pomelo red envelopes are the first red envelope DAPP on pomelo, making efforts to explore the application of EOS and expanding the scope of EOS's smart contracts and NFT applications. It draws on the idea of WeChat red envelopes and implements its functions on the blockchain. Due to the smooth trading status of EOS, the effect of grabbing red envelopes on blockchain is comparable to grabbing red envelopes on WeChat. Our red envelope grabbing technology has a wide range of usability. In the future, when the technology matures, it will be open source to the community, allowing all DAPPs with red envelope grabbing needs to use this technology for customized red envelope grabbing services. For anonymous banks, we develop anonymous smart contracts to achieve this goal by adding an additional layer of anonymity and privacy, making user transactions untraceable and protecting user privacy. Our privacy transfer technology has wide availability and will be open source to the community when the technology matures in the future, allowing all DAPPs with privacy transfer needs to use this technology for customized privacy service upgrades.
> If your application is a follow-up to a previous grant, please mention which one in the first line of the abstract and include a link to previous pull requests if applicable.
> Please delete these lines that start with a `>`

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [ ] **Level 1**:  Up to  $10,000, 2 approvals
- [x] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [x] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [ ] Online Search
- [ ] Hackathon
- [x] Other: Telegram chat

### CODE REVIEW

**Comment by eosdaoswap** [comment]
How Did You Hear About our grants program?

Chatting with Yves La Rose on a telegram, we sought help from the foundation and he also recommended a donation framework for me

**Comment by ABurton22** [comment]
Hi eosdaoswap,

In reviewing your application, is there a reason why there is an "*" beside the Yes in Open Sourced?

**Comment by eosdaoswap** [comment]
That's okay, our projects will all be open source

**Comment by eosdaoswap** [comment]
> Hi eosdaoswap,
> 
> In reviewing your application, is there a reason why there is an "*" beside the Yes in Open Sourced?

That's okay, our projects will all be open source

**Comment by eosdaoswap** [comment]
> Hello,
> 
> Please change your Milestones to show what still needs to be completed and they timeframe you intend to complete those items. Also, what is being done to complete each non completed item to make it complete, a scope of work for each item that you are requesting funding for is needed.
> 
> Thank you, Amy Burton

I have fixed it

**Comment by eosdaoswap** [comment]
Hello,Amy Burton

I have revised the application according to your request in the past few days!

Thank you,
Smith.Di  
2023/06/11

**Comment by eosdaoswap** [comment]
Thank you

**Comment by eosdaoswap** [comment]
Thank you

**Comment by eosdaoswap** [comment]
The Codebase has been deleted by me by mistake, and I am currently contacting github

**Comment by eosdaoswap** [comment]
It has been reopened, thank you

**Comment by eosdaoswap** [comment]
Can you indicate the reason for the closure?

**Comment by eosdaoswap** [comment]
Hi
Why are we closed? What is the reason?

**Comment by ABurton22** [comment]
Hi,

Your Grant Request was not approved. An email was sent yesterday to uabcontafed@gmail.com with the reasons.

Thank you,
Amy Burton

**Comment by eosdaoswap** [comment]
I don't quite understand the meaning of that email. Can someone guide me?
Also, did you resubmit according to the email prompts?

**Pull request closed without merging**
