### PR TITLE
alphaday.md

### PR DESCRIPTION
**Pull request by Mikael337**
### Project Abstract

Alphaday builds crypto experience dashboards for enthusiasts, developers, and projects. Users can drag and drop from hundreds of services, news and social feeds, charts, and dapp functionality to create their daily workflows inside a single dashboard. This eliminates the need to have multiple browser tabs open to get different bits of information. i.e. imagine having token prices, gas prices, twitter feed, latest news headlines, TVL, borrowing rates and any other information any user could possibly want all within one single dashboard. 

### For which grant [level](https://github.com/eosnetworkfoundation/grant-framework#grant-levels) are you applying?

- [x] **Level 1**:  Up to  $10,000, 2 approvals
- [ ] **Level 2**:  Up to  $50,000, 3 approvals
- [ ] **Level 3**:  Up to $200,000, 4 approvals

### Application Checklist

- [x] The [application template]([xxxx](https://github.com/eosnetworkfoundation/grant-framework/blob/main/applications/application-template.md)) has been copied, renamed (`my_project_name.md`) and updated.
- [x] The application file (`my_project_name.md`) has no spaces in its name, ends with the `.md` extension has been placed in the `applications` directory.
- [x] I have read and understood the:
  - [x] [FAQs](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/faq.md), 
  - [x] [application guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/grant_guidelines_per_category.md) and 
  - [x] [announcement guidelines](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/announcement-guidelines.md).
- [x] An EOS address for the payment of the milestones is provided inside the application.
- [x] I have read and acknowledge the [terms and conditions](https://github.com/eosnetworkfoundation/grant-framework/blob/main/docs/T&Cs.md).
- [x] The software delivered for this grant will be released under an open-source license specified in the application.
- [x] This project has NOT been part of a token sale or NFT sale.
- [x] The initial PR contains only one commit (squash and force-push if needed).
- [x] The grant will only be announced once the first milestone [has been accepted](https://github.com/eosnetworkfoundation/grant-milestones#process).

### How Did You Hear About our grants program?

- [ ] Social Media
- [ ] EOSNetwork.com
- [ ] Personal Recommendation
- [ ] ENF Fireside Chat
- [ ] Investor/VC
- [x] Online Search
- [ ] Hackathon
- [ ] Other: _______

### CODE REVIEW

**Comment by ABurton22** [comment]
The Grant Committee has approved this. The evaluators have been added to this PR. Please work with them to complete the approval process.

Thank you,
Amy Burton

**Comment by nsjames** [comment]
I foresee no technical blockers with this proposal.

If you need any assistance with the collection of some of the data (FAQ, Technical Whitepaper, EOS tokenomics information, etc) please reach out to me on telegram @RandomNobody

**Review by nsjames — APPROVED** [review]

**Comment by Mikael337** [comment]
Hello All,

Thank you for granting us the opportunity to build an EOS Dashboard.

We will begin to compile all relevant information regarding the EOS
dashboard.

Regards,
Michael

**Review by iamveritas — APPROVED** [review]
Looks good to me, looking forward to see EOS integrated! 🚀

**Review by lparisc — APPROVED** [review]
Looks like a sound project with actual deliverables already, realistic milestones, and measurable outcomes.

**Comment by tedcahalleos** [comment]
This grant has been fully approved.  You may now start to work on your milestones.  Please reference the automated email just sent to you.

**Pull request merged**
